//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApis
{
    using System;
    using System.Collections.Generic;
    
    public partial class cart
    {
        public cart()
        {
            this.cart_product = new HashSet<cart_product>();
            this.users = new HashSet<user>();
        }
    
        public int cart_id { get; set; }
        public int table_id { get; set; }
        public string cart_date { get; set; }
    
        public virtual table table { get; set; }
        public virtual ICollection<cart_product> cart_product { get; set; }
        public virtual ICollection<user> users { get; set; }
    }
}
