//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApis
{
    using System;
    using System.Collections.Generic;
    
    public partial class language
    {
        public language()
        {
            this.category_language = new HashSet<category_language>();
            this.product_language = new HashSet<product_language>();
        }
    
        public int language_id { get; set; }
        public string language_name { get; set; }
        public string language_short_name { get; set; }
        public string language_flag { get; set; }
        public bool language_is_active { get; set; }
    
        public virtual ICollection<category_language> category_language { get; set; }
        public virtual ICollection<product_language> product_language { get; set; }
    }
}
