//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApis
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public order()
        {
            this.order_details = new HashSet<order_details>();
        }
    
        public int order_id { get; set; }
        public int user_id { get; set; }
        public int table_id { get; set; }
        public string order_billing_number { get; set; }
        public string order_date_created { get; set; }
        public Nullable<bool> order_is_verified { get; set; }
        public bool order_is_completed { get; set; }
        public double order_total { get; set; }
        public int order_discount_type { get; set; }
        public double order_discount { get; set; }
        public int tax_id { get; set; }
        public Nullable<double> order_grand_total { get; set; }
    
        public virtual ICollection<order_details> order_details { get; set; }
        public virtual table table { get; set; }
        public virtual tax tax { get; set; }
        public virtual user user { get; set; }
    }
}
